Commit inicial
jhefborges/nossa-casa-codigo pull request #1
Opened 2019-11-11 00:44 UTC by jhefborges

Adicionados arquivos iniciais, gerados por https://start.spring.io/

Pull request referente ao issue inicial [https://trello.com/c/gn0aK45O](url)
Para participar do projeto @asouza

2019-11-11 02:53 UTC, asouza requested changes
opa, vou assumir que já um PR valendo. Nesse caso, faltou pegar as configurações web lá do start.spring.io

2019-11-11 14:40 UTC, jhefborges commented
Acredito que era isso que faltava, adicionei a configuração do postgres.
Recomenda alguma forma e ferramenta de teste?

2019-11-12 01:17 UTC, asouza approved these changes
Aqui está ótimo! Em relação aos testes, acho que podemos esperar um pouco mais para ver que tipo de funcionalidade vai ser necessária. Vamo que vamo!

2019-11-12 01:17 UTC, asouza commented on nossacasacodigo/pom.xml
> +		<dependency>
interessante aqui, não conhecia esse :).

2019-11-18 04:15 UTC, merged